name: a4s_sealer_module
services:
  a4s_sealer_module:
    container_name: a4s_sealer_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m a4s_sealer_rest_node --port 3057 --device ${A4S_DEVICE}
    env_file: .env
    volumes:
      - /dev:/dev
      - ./src:/home/app/a4s_sealer_module/src
      - ./tests:/home/app/a4s_sealer_module/tests
    ports:
      - 3057:3057
    privileged: True
